eureka:
    client:
        fetchRegistry: true
        registerWithEureka: false
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: http://192.168.99.57:18000/eureka/,http://192.168.100.25:18000/eureka/
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
        lease-expiration-duration-in-seconds: 90
        lease-renewal-interval-in-seconds: 30
        metadata-map:
            cluster: CLOUDPLATFORM-HYSTRIX-AGGREGATE
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 60000
ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 60000
management:
    security:
        enabled: false
security:
    oauth2:
        client:
            #accessTokenUri: http://localhost:15000/auth/oauth/token
            accessTokenUri: http://www.baidu.com
            clientId: acme
            clientSecret: acmesecret
            #userAuthorizationUri: http://localhost:15000/auth/oauth/authorize
            userAuthorizationUri: http://sso.huashenghaoche.com/login?service=http://oa.huashenghaoche.com/index.jsp
        resource:
            loadBalanced: true
            userInfoUri: http://certid/auth/user
spring:
    aop:
        proxy-target-class: true
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        jackson:
            default-property-inclusion: non_null
        messages:
            encoding: UTF-8
zuul:
    routes:
        cmall:
            path: /manager-api/cmall/v1/**
            serviceId: cmalladmin
        basefunction:
            path: /manager-api/bf/v1/**
            serviceId: basefunction
        cargoods:
            path: /manager-api/cargoods/v1/**
            serviceId: cargoods
        carinfo:
            path: /manager-api/carinfo/v1/**
            serviceId: carinfo
        carorder:
            path: /manager-api/carorder/v1/**
            serviceId: carorder
        picture:
            path: /manager-api/picture/v1/**
            serviceId: pictureservice
hshc:
    auth:
        url: http://lkl.wx.huashenghaoche.com
        introduceUrl: /front-api/unauth/
    security:
        authedUrl: /front-api/unauth/**
    restTemplate:
            pool:
                defaultMaxPerRoute: 200
                maxTotal: 200
            timeout:
                connectTimeout: 5000
                connectionRequestTimeout: 5000
                readTimeout: 60000